### ISSUE TITLE
Dashboard won't restart after crash from bad function call

### ISSUE THREAD

**Issue by gnomaditr0n** [blockapps/issues#5]
* Dashboard
 *  1.1
 * Private Instance
 * Ubuntu 14.0.4 LTS trusty
 * Docker version 1.11.2, build b9f10c9

STEPS:
 * Perform Issue #4
 * Run bash on the dashboard VM, and try to restart the docker image

EXPECTED:
The docker image will restart and the dashboard will be accessible

ACTUAL:
The dashboard docker image crashes on startup

LOGS:
Express server listening on 9000, in development mode
THIS IS WORKING====================
GET /stats 200 48.331 ms - -
bloc is listening on http://0.0.0.0:8000

api is pointed to http://11.24.82.5 with profile strato-dev

/usr/lib/strato/bloc-server/bin/main.js:338
          throw err;
          ^
events.js:154

**Comment by kejace** [comment]
Closing this due to upgrade to `1.2`. Let's reopen if issue persist.
